# Generated by Django 5.1.2 on 2024-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='action',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=10),
        ),
    ]
